####################################################################
# SITE CONFIGURATION
####################################################################
# 1. Site Settings
# 2. Gem Settings
# 3. Comments Settings
# 4. Jekyll Settings
# 5. Site Favicons & Manifest Icons
# 6. Collections
# 7. Jekyll Defaults
# 8. Installed Gems
# --------- EDIT LIMIT ---------
# Build Settings
# Read Config
# Filtering
# Conversion
# Markdown Settings
# Serving
# Output
# SASS Config
# HTML Compression
# File Exclusions
####################################################################

####################################################################
# 1. SITE SETTINGS
####################################################################
title               : "RedEyed RPG"
tagline             : "Content, Maps, & Software for your favourite TTRPGs"
description         : "RedEyed RPG produces content and software for a variety of Table Top Role Playing Game systems"
logo                : "/assets/img/logo/597x597-RPG-R-Circle-320.png"
url                 : "https://www.redeyed-rpg.com"
baseurl             : ""
theme               : "redeyed-jekyll-theme"
repo                : "https://github.com/RedEyed-RPG/redeyed-jekyll-theme"
email               : "ragdata@redeyed-rpg.com"
date_format         : "%-d %B %Y"
encoding            : utf-8
lang                : en-AU
locale              : en_AU
css_inline          : false
# google_analytics    :
# google_site_verification:                   # jekyll-seo-tag
# google_analytics_anonymize_ip:
# short_name:
pwa:                                        # pwa mode config
    enabled: true
#    service_worker:
toc: true                                   # table of contents - global switch
theme_mode: dark                            # custom config option: [light|dark|brew]
copyright: "Copyright (c) 2022 ~ {author} & RedEyed-RPG ~ Some Rights Reserved"

####################################################################
# 2. GEM SETTINGS
####################################################################
feed:                                       # jekyll-feed
    path: /blog/feed.atom                   # jekyll-feed > feed path



#pagination:                                 # jekyll-paginate-v2
#    enabled: false                           # jekyll-paginate-v2 > enabled
#    debug: false                            # jekyll-paginate-v2 > debug mode
#    collection: posts                       # jekyll-paginate-v2 > default collection to paginate
#    per_page: 10                            # jekyll-paginate-v2 > results per page
#    permalink: 'page/:num:output_ext'       # jekyll-paginate-v2 > permalink format
#    title: ':title - page :num'             # jekyll-paginate-v2 > title format
#    limit: 0                                # jekyll-paginate-v2 > limit
#    sort_field: date                        # jekyll-paginate-v2 > sort field
#    sort_reverse: true                      # jekyll-paginate-v2 > reverse sort option
#    category: posts                         # jekyll-paginate-v2 > category
#    trail:                                  # jekyll-paginate-v2 > page link trail
#        before: 2                           # jekyll-paginate-v2 > number of page links to show before current
#        after: 2                            # jekyll-paginate-v2 > number of page links to show after current
#    extension: html                         # jekyll-paginate-v2 > default page extension
#    indexpage: index                        # jekyll-paginate-v2 > name of index page

jekyll-mentions: https://twitter.com        # jekyll-mentions > service used when @replying

twitter:                                    # jekyll-seo-tag > twitter properties
    username: RedeyedRPG                    # jekyll-seo-tag > owner's twitter handle
author: Ragdata                             # jekyll-seo-tag > default author
social:                                     # jekyll-seo-tag > social overrides
    name: Ragdata                           # jekyll-seo-tag > real name
    links:                                  # jekyll-seo-tag > social aliases
        - https://patreon.com/ragdata       # jekyll-seo-tag > Your Patreon Profile URL
        - https://github.com/ragdata        # jekyll-seo-tag > Your GitHub Profile URL
        - https://twitter.com/RedeyedRPG    # jekyll-seo-tag > Your Twitter Profile URL
        - https://reddit.com/r/redeyed-rpg  # jekyll-seo-tag > Your Subreddit URL
        - https://facebook.com/RedeyedRPG   # jekyll-seo-tag > Your Facebook Page URL
        - https://redeyed-rpg.tumblr.com    # jekyll-seo-tag > Your Tumblr Blog URL
        - https://keybase.io/ragdata        # jekyll-seo-tag > Your Keybase Profile URL

jekyll-archives:                            # jekyll-archives
    enabled: [categories, tags]             # jekyll-archives > enabled
    layouts:
        category: category                  # jekyll-archives > category
        tag: tag                            # jekyll-archives > tag
    permalinks:
        year: /:year/                       # jekyll-archives > year permalink
        month: /:year/:month/               # jekyll-archives > month permalink
        day: /:year/:month/:day/            # jekyll-archives > day permalink
        category: /cat/:name/               # jekyll-archives > category permalink
        tag: /tag/:name                     # jekyll-archives > tag permalink

redirect_from:                              # jekyll-redirect-from
    json: false                             # jekyll-redirect-from > include redirects.json in output

####################################################################
# 3. COMMENTS SETTINGS
####################################################################
comments:
    active: false
#    # DISQUS
#    disqus:
#        shortname:
#    # UTTERANCES > https://utteranc.es
#    utterances:
#        repo:
#        issue_term:
#    # GISCUS > https://giscus.app
#    giscus:
#        repo:                               # <gh-username>/<repo>
#        repo_id:
#        category:
#        category_id:
#        mapping:                            # optional: defaults to 'pathname'
#        input_position:                     # optional: defaults to 'bottom'
#        lang:                               # optional: defaults to the value of `site.lang`

####################################################################
# 4. JEKYLL SETTINGS
####################################################################
sass:
    style: compressed                       # style compression
    sass_dir: ../_sass
permalink: date                             # permalink style (YYYY/MM/DD/page-name)
excerpt_separator: <!-- more -->            # marks end of excerpt in posts
timezone: Australia/Brisbane                # timezone for blog and posts
paginate: 10                                # paginate - # of items per page
paginate_path: /page:num                    # paginate - default page slug for pages

####################################################################
# 5. SITE FAVICONS & MANIFEST ICONS
####################################################################
favicons:
    16: assets/img/favicons/favicons-16x16.png
    32: assets/img/favicons/favicons-32x32.png
    180: assets/img/favicons/apple-touch-icon.png
    192: assets/img/favicons/android-chrome-192x192.png
    270: assets/img/favicons/mstile-150x150.png
    512: assets/img/favicons/android-chrome-512x512.png

####################################################################
# 6. COLLECTIONS
####################################################################
# collections:
#     posts:
#         title: Posts
#         output: true
#         description: "My Thoughts & Ideas"
#         feature_text: |
#             Welcome to the blog
#         feature_image:

####################################################################
# 7. JEKYLL DEFAULTS
####################################################################
defaults:
    -
        scope:
            path: ""
        values:
            layout: default
    -
        scope:
            path: _posts
        values:
            layout: post
            comments: true
            toc: true
            permalink: /blog/:title:output_ext
    -
        scope:
            path: ""
            type: pages
        values:
            layout: page
    -
        scope:
            path: _drafts
        values:
            comments: false
            sitemap: false
    -
        scope:
            path: assets/img/favicons
        values:
            swcache: true
    -
        scope:
            path: assets/js/dist
        values:
            swcache: true

####################################################################
# 8. INSTALLED GEMS
####################################################################
plugins:
    - jemoji
    - jekyll-toc
    - jekyll-feed
    - jekyll-seo-tag
    - jekyll-archives
    - jekyll-sitemap
    - jekyll-mentions
    - jekyll-paginate
    - jekyll-spaceship
    - jekyll-pluralize
#    - jekyll-paginate-v2
#    - jekyll-include-cache
    - jekyll-redirect-from
    - jekyll-email-protect
    - jekyll-tagging-related_posts

####################################################################
############### DO NOT EDIT BELOW THIS LINE ########################
########## UNLESS YOU REALLY KNOW WHAT YOU'RE DOING ################
####################################################################

####################################################################
# BUILD SETTINGS
####################################################################
source: src
#destination: _site
#collections_dir: _data
#data_dir: _data
#plugins_dir: _plugins
#layouts_dir: _layouts
#includes_dir: _includes

####################################################################
# READ CONFIG
####################################################################
safe: false
include: [".htaccess"]
keep_files: [".git",".svn"]
markdown_ext: markdown,mkdown,mkdn,mkd,md
strict_front_matter: false

####################################################################
# FILTERING
####################################################################
show_drafts: false
limit_posts: 0
future: false
unpublished: false

####################################################################
# CONVERSION
####################################################################
highlighter: rouge
lsi: false
incremental: false

####################################################################
# MARKDOWN SETTINGS
####################################################################
markdown: kramdown         # markdown parser settings
kramdown:
    syntax_highlighter: rouge
    syntax_highlighter_opts:
        css_class: highlight
        # default_lang: console
        span:
            line_numbers: false
        block:
            line_numbers: true
            start_line: 1

####################################################################
# SERVING
####################################################################
detach: false
port: 4000
host: localhost
show_dir_listing: false
assets:
    self-host:
        enabled: false
        env: development
####################################################################
# OUTPUT
####################################################################
quiet: false
verbose: false
liquid:
    error_mode: warn
    strict_filters: false
    strict_variables: false

####################################################################
# HTML COMPRESSION
####################################################################
compress_html:
    clippings: all
    comments: all
    endings: all
    profile: false
    blanklines: false
    ignore:
        envs: [development]

####################################################################
# FILE EXCLUSIONS
####################################################################
# The following items will not be processed by default.
# Any item listed under the `exclude:` key here will be automatically
# added to the internal "default list"
#
# Excluded items can be processed by explicitly listing their file
# paths under the `include:` key
exclude:
    - '*.gem'
    - '*.gemspec'
    - .github
    - bin
    - gulpfile.js
    - README.md
    - CHANGELOG.md
    - LICENSE
    - package*.json
    - node_modules
    - vendor
